export const API_ENDPOINTS = {
  health: '/api/health',
  appConfig: '/api/app/config',
  home: '/api/home',
  newsCategories: '/api/news/categories',
  newsList: '/api/news',
  newsDetail: (id: string) => `/api/news/${id}`,
  brand: '/api/brand',
  brandArticles: '/api/brand/articles',
  brandArticleDetail: (id: string) => `/api/brand/articles/${id}`,
  productCategories: '/api/products/categories',
  products: '/api/products',
  productDetail: (id: string) => `/api/products/${id}`,
  caseCategories: '/api/cases/categories',
  cases: '/api/cases',
  caseDetail: (id: string) => `/api/cases/${id}`,
  services: '/api/services',
  serviceDetail: (id: string) => `/api/services/${id}`,
  kbLifeEntries: '/api/kb-life/entries',
  kbLifeCanteen: '/api/kb-life/canteen',
  kbLifeShuttle: '/api/kb-life/shuttle',
  kbLifeActivities: '/api/kb-life/activities',
  profile: '/api/profile',
} as const;
