export const API_ENDPOINTS = {
  health: '/api/health',
  appConfig: '/api/app/config',
  home: '/api/home',
  newsCategories: '/api/news/categories',
  newsList: '/api/news',
  newsDetail: (id: string) => `/api/news/${id}`,
  brand: '/api/brand',
  brandArticles: '/api/brand/articles',
  brandArticleDetail: (id: string) => `/api/brand/articles/${id}`,
  productCategories: '/api/products/categories',
  products: '/api/products',
  productDetail: (id: string) => `/api/products/${id}`,
  caseCategories: '/api/cases/categories',
  cases: '/api/cases',
  caseDetail: (id: string) => `/api/cases/${id}`,
  services: '/api/services',
  serviceDetail: (id: string) => `/api/services/${id}`,
  serviceInsights: '/api/services/insights',
  serviceInsightDetail: (id: string) => `/api/services/insights/${id}`,
  kbLifeEntries: '/api/kb-life/entries',
  kbLifeCanteen: '/api/kb-life/canteen',
  kbLifeShuttle: '/api/kb-life/shuttle',
  kbLifeActivities: '/api/kb-life/activities',
  kbLifeWetalk: '/api/kb-life/wetalk',
  kbLifeWetalkDetail: (id: string) => `/api/kb-life/wetalk/${id}`,
  kbLifeCampusMap: '/api/kb-life/campus-map',
  kbLifeHolidayCalendar: '/api/kb-life/holiday-calendar',
  profile: '/api/profile',
} as const;
